/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-02-05 19:12:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login In</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Quicksand');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: 'Quicksand', sans-serif;\r\n");
      out.write("\ttransition: .5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container label {\r\n");
      out.write("\tfont-size: 1.4rem;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: rgba(150, 150, 220, .9);\r\n");
      out.write("\tline-height: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container img.profile {\r\n");
      out.write("\tborder: 4px solid rgba(150, 150, 220, .9);\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .message-warning {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tleft: 140%;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-flow: row nowrap;\r\n");
      out.write("\tjustify-content: space-around;\r\n");
      out.write("\talign-items: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .message-warning img {\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .message-warning div {\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor: rgba(240, 240, 240, 1);\r\n");
      out.write("\tbackground-color: rgba(50, 50, 50, .9);\r\n");
      out.write("\tpadding: .4rem;\r\n");
      out.write("\tfont-family: 'Quicksand', sans-serif;\r\n");
      out.write("\tfont-size: 1.1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .container-input input:invalid {\r\n");
      out.write("\tcolor: rgba(250, 100, 100, .7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container input {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tpadding-left: .9rem;\r\n");
      out.write("\tpadding-right: .9rem;\r\n");
      out.write("\tpadding-top: 1.4rem;\r\n");
      out.write("\tpadding-bottom: .9rem;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tfont-size: 1.2rem;\r\n");
      out.write("\tborder: 2px solid rgba(127, 127, 127, .9);\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: rgba(60, 60, 210, .9);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-input input:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder: 2px solid rgba(0, 0, 0, 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-input input:focus ~.sub-placeholder {\r\n");
      out.write("\ttransform: scale(.9);\r\n");
      out.write("\ttop: .4rem;\r\n");
      out.write("\tleft: .4rem;\r\n");
      out.write("\tcolor: rgba(200, 200, 250, 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-input input:valid ~.sub-placeholder {\r\n");
      out.write("\ttransform: scale(.9);\r\n");
      out.write("\ttop: .4rem;\r\n");
      out.write("\tleft: .4rem;\r\n");
      out.write("\tcolor: rgba(200, 200, 250, 1);\r\n");
      out.write("}\r\n");
      out.write("/*\r\n");
      out.write(".container-input input:invalid{\r\n");
      out.write("  border: 2px solid rgba(250, 79, 79, .9);\r\n");
      out.write("  animation: error .8s infinite ease, error-tresh .2s infinite ease;\r\n");
      out.write("}*/\r\n");
      out.write(".container-input input:valid {\r\n");
      out.write("\tborder: 2px solid rgba(79, 250, 79, .9);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-input {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub-placeholder {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 1.1rem;\r\n");
      out.write("\tleft: 1.1rem;\r\n");
      out.write("\tcolor: rgba(200, 200, 250, 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .loginin {\r\n");
      out.write("\tmargin-left: 1.2rem;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tbackground-color: rgba(110, 110, 220, .9);\r\n");
      out.write("\tcursive: pointer;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes error { 0%{ //\r\n");
      out.write("\ttransform: translate(0px, 0px);\r\n");
      out.write("\tborder: 2px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("50%{\r\n");
      out.write("//\r\n");
      out.write("transform\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("translate\r\n");
      out.write("(-2px\r\n");
      out.write(",\r\n");
      out.write("0\r\n");
      out.write("px\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("border\r\n");
      out.write(":\r\n");
      out.write("2px\r\n");
      out.write(" \r\n");
      out.write("solid\r\n");
      out.write(" \r\n");
      out.write("rgba\r\n");
      out.write("(250\r\n");
      out.write(",\r\n");
      out.write("120,\r\n");
      out.write("120,\r\n");
      out.write(".4\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("95%{\r\n");
      out.write("border\r\n");
      out.write(":\r\n");
      out.write("2px\r\n");
      out.write(" \r\n");
      out.write("solid\r\n");
      out.write(" \r\n");
      out.write("rgba\r\n");
      out.write("(250\r\n");
      out.write(",\r\n");
      out.write("120,\r\n");
      out.write("120,\r\n");
      out.write(".4\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes error-tresh { 0%{\r\n");
      out.write("\ttransform: translate(0px, 0px); //\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write("50%{\r\n");
      out.write("transform\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("translate\r\n");
      out.write("(-1px\r\n");
      out.write(",\r\n");
      out.write("0\r\n");
      out.write("px\r\n");
      out.write(");\r\n");
      out.write("//background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("rgba\r\n");
      out.write("(250\r\n");
      out.write(",\r\n");
      out.write("120,\r\n");
      out.write("//120,\r\n");
      out.write(".4\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("95%{\r\n");
      out.write("//\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("rgba\r\n");
      out.write("(250\r\n");
      out.write(",\r\n");
      out.write("120,\r\n");
      out.write("//120,\r\n");
      out.write(".4\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("transform\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("translate\r\n");
      out.write("(1px\r\n");
      out.write(",\r\n");
      out.write("0\r\n");
      out.write("px\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"message-warning\">\r\n");
      out.write("\t\t\t<img\r\n");
      out.write("\t\t\t\tsrc=\"https://i.mycdn.me/image?id=849385275135&t=3&plc=WEB&tkn=*EE_9G06WUxjnLaPnRuKfF410TPM\"></img>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<img class=\"profile\"\r\n");
      out.write("\t\t\tsrc=\"https://intelinvest.ru/resources/images/index/section3/3.png;jsessionid=2b69fbf781265cbdd33b6c5b3179\"\r\n");
      out.write("\t\t\talt=\"Photo of profile\" />\r\n");
      out.write("\t\t<form action=\"Login\" method=\"post\">\r\n");
      out.write("\t\t\t<label for=\"uname\">UserName</label>\r\n");
      out.write("\t\t\t<div class=\"container-input\">\r\n");
      out.write("\t\t\t\t<input id=\"uname\" class=\"uname\" type=\"text\" name=\"uname\"></input> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sub-placeholder\">UserName</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t<div class=\"container-input\">\r\n");
      out.write("\t\t\t\t<input id=\"password\" class=\"password\" type=\"password\" name=\"password\"></input> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sub-placeholder\">your password</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input class=\"loginin\" type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<a href=\"aboutUs.jsp\">AboutUs</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
